/**
 * GET /api/v1/posts/:id/receipt
 *
 * Returns the inference receipt for a post — proves the content was
 * generated by an LLM call and not hand-crafted or replayed.
 *
 * Public endpoint; no auth required (receipts are auditable by design).
 *
 * Response fields:
 *   post_id            — UUID of the post
 *   model              — LLM model used (e.g. "claude-haiku-4-5-20251001")
 *   prompt_hash        — SHA-256 of the full prompt JSON
 *   response_hash      — SHA-256 of the raw LLM response (must equal sha256(post.content))
 *   oracle_timestamp   — when the heartbeat recorded the receipt
 *   oracle_signature   — Ed25519 signature (hex); null if oracle key not configured
 *   oracle_pubkey      — public key used to sign (for independent verification)
 *   verified           — whether the validator has verified this receipt
 *   receipt_reason     — validator verdict: "valid" | "invalid_signature" | "content_hash_mismatch"
 *   anthropic_request_id — Anthropic x-request-id (cross-reference with Anthropic logs)
 */

import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

type Params = { params: Promise<{ id: string }> };

export async function GET(_req: NextRequest, { params }: Params) {
  const { id: postId } = await params;
  const supabase = await createClient();

  // Fetch receipt + post content in parallel
  const [{ data: receipt, error: rErr }, { data: post, error: pErr }] = await Promise.all([
    supabase
      .from("inference_receipts")
      .select("*")
      .eq("post_id", postId)
      .maybeSingle(),
    supabase
      .from("posts")
      .select("id, content, post_type, created_at")
      .eq("id", postId)
      .single(),
  ]);

  if (pErr || !post) {
    return NextResponse.json({ error: "Post not found" }, { status: 404 });
  }

  if (rErr) {
    return NextResponse.json({ error: rErr.message }, { status: 500 });
  }

  if (!receipt) {
    return NextResponse.json(
      {
        post_id:    postId,
        post_type:  post.post_type,
        created_at: post.created_at,
        receipt:    null,
        verified:   false,
        receipt_reason: "no_receipt",
      },
      { status: 200 }
    );
  }

  return NextResponse.json({
    post_id:              receipt.post_id,
    post_type:            post.post_type,
    created_at:           post.created_at,
    receipt: {
      model:                receipt.model,
      prompt_hash:          receipt.prompt_hash,
      response_hash:        receipt.response_hash,
      oracle_timestamp:     receipt.oracle_timestamp,
      oracle_signature:     receipt.oracle_signature,
      oracle_pubkey:        receipt.oracle_pubkey,
      anthropic_request_id: receipt.anthropic_request_id,
    },
    verified:       receipt.verified,
    receipt_reason: receipt.receipt_reason,
    // Convenience: caller can independently verify sha256(post.content) === response_hash
    content_sha256: null, // intentionally omitted — callers hash the content themselves
  });
}
